using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SAP_Core.BO
{
    public class QuotationBO
    {
        public string Autorizado { get; set; }
        public string CardCode { get; set; }
        public string DocDate { get; set; }
        public int DocEntry { get; set; }
        public string DocNum { get; set; }
        public string StatusAproveed { get; set; }
        public string ReadyGenerateOv { get; set; }
        public double DocumentTotal { get; set; }
        public string CardName { get; set; }
        public string Object { get; set; }
        public string LicTradNum { get; set; }
        public int SlpCode { get; set; }
        public string SalesOrder { get; set; }
        public string ApprovalCommentary { get; set; }
        public string Mobile_ID { get; set; }
    }
    public class ListQuotation
    {
        public List<QuotationBO> Quotation { get; set; }
    }


    public class Rootobject
    {
        public string odatametadata { get; set; }
        public string U_VIS_DeliveryDateOptional { get; set; }
        public string U_ID_Document { get; set; }
        public string odataetag { get; set; }
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string DocType { get; set; }
        public string HandWritten { get; set; }
        public string Printed { get; set; }
        public string DocDate { get; set; }
        public string DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Address { get; set; }
        public object NumAtCard { get; set; }
        public float DocTotal { get; set; }
        public object AttachmentEntry { get; set; }
        public string DocCurrency { get; set; }
        public float DocRate { get; set; }
        public string Reference1 { get; set; }
        public object Reference2 { get; set; }
        public object Comments { get; set; }
        public string JournalMemo { get; set; }
        public int PaymentGroupCode { get; set; }
        public string DocTime { get; set; }
        public int SalesPersonCode { get; set; }
        public int TransportationCode { get; set; }
        public string Confirmed { get; set; }
        public object ImportFileNum { get; set; }
        public string SummeryType { get; set; }
        public string ShowSCN { get; set; }
        public int Series { get; set; }
        public string TaxDate { get; set; }
        public string PartialSupply { get; set; }
        public string DocObjectCode { get; set; }
        public string ShipToCode { get; set; }
        public object Indicator { get; set; }
        public string FederalTaxID { get; set; }
        public float DiscountPercent { get; set; }
        public object PaymentReference { get; set; }
        public string CreationDate { get; set; }
        public string UpdateDate { get; set; }
        public int FinancialPeriod { get; set; }
        public int UserSign { get; set; }
        public object TransNum { get; set; }
        public float VatSum { get; set; }
        public float VatSumSys { get; set; }
        public float VatSumFc { get; set; }
        public string NetProcedure { get; set; }
        public float DocTotalFc { get; set; }
        public float DocTotalSys { get; set; }
        public object Form1099 { get; set; }
        public object Box1099 { get; set; }
        public string RevisionPo { get; set; }
        public object RequriedDate { get; set; }
        public object CancelDate { get; set; }
        public string BlockDunning { get; set; }
        public string Submitted { get; set; }
        public int Segment { get; set; }
        public string PickStatus { get; set; }
        public string Pick { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentBlock { get; set; }
        public object PaymentBlockEntry { get; set; }
        public object CentralBankIndicator { get; set; }
        public string MaximumCashDiscount { get; set; }
        public string Reserve { get; set; }
        public object Project { get; set; }
        public object ExemptionValidityDateFrom { get; set; }
        public object ExemptionValidityDateTo { get; set; }
        public string WareHouseUpdateType { get; set; }
        public string Rounding { get; set; }
        public object ExternalCorrectedDocNum { get; set; }
        public object InternalCorrectedDocNum { get; set; }
        public object NextCorrectingDocument { get; set; }
        public string DeferredTax { get; set; }
        public object TaxExemptionLetterNum { get; set; }
        public float WTApplied { get; set; }
        public float WTAppliedFC { get; set; }
        public string BillOfExchangeReserved { get; set; }
        public object AgentCode { get; set; }
        public float WTAppliedSC { get; set; }
        public float TotalEqualizationTax { get; set; }
        public float TotalEqualizationTaxFC { get; set; }
        public float TotalEqualizationTaxSC { get; set; }
        public int NumberOfInstallments { get; set; }
        public string ApplyTaxOnFirstInstallment { get; set; }
        public float WTNonSubjectAmount { get; set; }
        public float WTNonSubjectAmountSC { get; set; }
        public float WTNonSubjectAmountFC { get; set; }
        public float WTExemptedAmount { get; set; }
        public float WTExemptedAmountSC { get; set; }
        public float WTExemptedAmountFC { get; set; }
        public float BaseAmount { get; set; }
        public float BaseAmountSC { get; set; }
        public float BaseAmountFC { get; set; }
        public float WTAmount { get; set; }
        public float WTAmountSC { get; set; }
        public float WTAmountFC { get; set; }
        public object VatDate { get; set; }
        public int DocumentsOwner { get; set; }
        public object FolioPrefixString { get; set; }
        public object FolioNumber { get; set; }
        public string DocumentSubType { get; set; }
        public object BPChannelCode { get; set; }
        public object BPChannelContact { get; set; }
        public string Address2 { get; set; }
        public string DocumentStatus { get; set; }
        public string PeriodIndicator { get; set; }
        public string PayToCode { get; set; }
        public object ManualNumber { get; set; }
        public string UseShpdGoodsAct { get; set; }
        public string IsPayToBank { get; set; }
        public object PayToBankCountry { get; set; }
        public object PayToBankCode { get; set; }
        public object PayToBankAccountNo { get; set; }
        public object PayToBankBranch { get; set; }
        public object BPL_IDAssignedToInvoice { get; set; }
        public float DownPayment { get; set; }
        public string ReserveInvoice { get; set; }
        public int LanguageCode { get; set; }
        public object TrackingNumber { get; set; }
        public object PickRemark { get; set; }
        public object ClosingDate { get; set; }
        public object SequenceCode { get; set; }
        public object SequenceSerial { get; set; }
        public object SeriesString { get; set; }
        public object SubSeriesString { get; set; }
        public string SequenceModel { get; set; }
        public string UseCorrectionVATGroup { get; set; }
        public float TotalDiscount { get; set; }
        public float DownPaymentAmount { get; set; }
        public float DownPaymentPercentage { get; set; }
        public string DownPaymentType { get; set; }
        public float DownPaymentAmountSC { get; set; }
        public float DownPaymentAmountFC { get; set; }
        public float VatPercent { get; set; }
        public object ServiceGrossProfitPercent { get; set; }
        public object OpeningRemarks { get; set; }
        public object ClosingRemarks { get; set; }
        public float RoundingDiffAmount { get; set; }
        public float RoundingDiffAmountFC { get; set; }
        public float RoundingDiffAmountSC { get; set; }
        public string Cancelled { get; set; }
        public object SignatureInputMessage { get; set; }
        public object SignatureDigest { get; set; }
        public object CertificationNumber { get; set; }
        public object PrivateKeyVersion { get; set; }
        public string ControlAccount { get; set; }
        public string InsuranceOperation347 { get; set; }
        public string ArchiveNonremovableSalesQuotation { get; set; }
        public object GTSChecker { get; set; }
        public object GTSPayee { get; set; }
        public int ExtraMonth { get; set; }
        public int ExtraDays { get; set; }
        public int CashDiscountDateOffset { get; set; }
        public string StartFrom { get; set; }
        public string NTSApproved { get; set; }
        public object ETaxWebSite { get; set; }
        public object ETaxNumber { get; set; }
        public object NTSApprovedNumber { get; set; }
        public string EDocGenerationType { get; set; }
        public object EDocSeries { get; set; }
        public object EDocNum { get; set; }
        public object EDocExportFormat { get; set; }
        public string EDocStatus { get; set; }
        public object EDocErrorCode { get; set; }
        public object EDocErrorMessage { get; set; }
        public string DownPaymentStatus { get; set; }
        public object GroupSeries { get; set; }
        public object GroupNumber { get; set; }
        public string GroupHandWritten { get; set; }
        public object ReopenOriginalDocument { get; set; }
        public object ReopenManuallyClosedOrCanceledDocument { get; set; }
        public string CreateOnlineQuotation { get; set; }
        public object POSEquipmentNumber { get; set; }
        public object POSManufacturerSerialNumber { get; set; }
        public object POSCashierNumber { get; set; }
        public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
        public string ClosingOption { get; set; }
        public object SpecifiedClosingDate { get; set; }
        public string OpenForLandedCosts { get; set; }
        public string AuthorizationStatus { get; set; }
        public float TotalDiscountFC { get; set; }
        public float TotalDiscountSC { get; set; }
        public string RelevantToGTS { get; set; }
        public object BPLName { get; set; }
        public object VATRegNum { get; set; }
        public object AnnualInvoiceDeclarationReference { get; set; }
        public object Supplier { get; set; }
        public object Releaser { get; set; }
        public object Receiver { get; set; }
        public object BlanketAgreementNumber { get; set; }
        public string IsAlteration { get; set; }
        public string CancelStatus { get; set; }
        public object AssetValueDate { get; set; }
        public string DocumentDelivery { get; set; }
        public object AuthorizationCode { get; set; }
        public object StartDeliveryDate { get; set; }
        public object StartDeliveryTime { get; set; }
        public object EndDeliveryDate { get; set; }
        public object EndDeliveryTime { get; set; }
        public object VehiclePlate { get; set; }
        public object ATDocumentType { get; set; }
        public object ElecCommStatus { get; set; }
        public object ElecCommMessage { get; set; }
        public string ReuseDocumentNum { get; set; }
        public string ReuseNotaFiscalNum { get; set; }
        public string PrintSEPADirect { get; set; }
        public object FiscalDocNum { get; set; }
        public object POSDailySummaryNo { get; set; }
        public object POSReceiptNo { get; set; }
        public object PointOfIssueCode { get; set; }
        public object Letter { get; set; }
        public object FolioNumberFrom { get; set; }
        public object FolioNumberTo { get; set; }
        public string InterimType { get; set; }
        public int RelatedType { get; set; }
        public object RelatedEntry { get; set; }
        public object SAPPassport { get; set; }
        public object DocumentTaxID { get; set; }
        public object DateOfReportingControlStatementVAT { get; set; }
        public object ReportingSectionControlStatementVAT { get; set; }
        public string ExcludeFromTaxReportControlStatementVAT { get; set; }
        public object POS_CashRegister { get; set; }
        public string UpdateTime { get; set; }
        public object CreateQRCodeFrom { get; set; }
        public object PriceMode { get; set; }
        public string ShipFrom { get; set; }
        public string CommissionTrade { get; set; }
        public string CommissionTradeReturn { get; set; }
        public string UseBillToAddrToDetermineTax { get; set; }
        public object Cig { get; set; }
        public object Cup { get; set; }
        public object FatherCard { get; set; }
        public string FatherType { get; set; }
        public object ShipState { get; set; }
        public object ShipPlace { get; set; }
        public object CustOffice { get; set; }
        public object FCI { get; set; }
        public object AddLegIn { get; set; }
        public object LegTextF { get; set; }
        public object DANFELgTxt { get; set; }
        public string IndFinal { get; set; }
        public int DataVersion { get; set; }
        public string U_SYP_MDMT { get; set; }
        public object U_SYP_MDTD { get; set; }
        public object U_SYP_MDSD { get; set; }
        public object U_SYP_MDCD { get; set; }
        public string U_SYP_STATUS { get; set; }
        public object U_SYP_MDTO { get; set; }
        public object U_SYP_MDSO { get; set; }
        public object U_SYP_MDCO { get; set; }
        public object U_SYP_FECHAREF { get; set; }
        public object U_SYP_MOTNCND { get; set; }
        public string U_SYP_DETPAGADO { get; set; }
        public string U_SYP_AUTODET { get; set; }
        public object U_SYP_DETPAY { get; set; }
        public object U_SYP_NGUIA { get; set; }
        public object U_SYP_NOCCLIENTE { get; set; }
        public object U_SYP_NANTICIPO { get; set; }
        public string U_SYP_TCOMPRA { get; set; }
        public string U_SYP_ANTICIPO { get; set; }
        public float U_SYP_PANTICIPO { get; set; }
        public object U_SYP_COTPROV { get; set; }
        public object U_SYP_CARPIMP { get; set; }
        public object U_SYP_DPFC { get; set; }
        public object U_SYP_DPNM { get; set; }
        public object U_SYP_MDFE { get; set; }
        public object U_SYP_MDND { get; set; }
        public string U_SYP_CDAD { get; set; }
        public object U_SYP_MDFD { get; set; }
        public object U_SYP_CODERCC { get; set; }
        public string U_SYP_TREQUE { get; set; }
        public object U_SYP_TIPOBOLETO { get; set; }
        public object U_SYP_TEMBAR { get; set; }
        public object U_SYP_NUMCRET { get; set; }
        public object U_SYP_MDCT { get; set; }
        public object U_SYP_MDRT { get; set; }
        public object U_SYP_MDNT { get; set; }
        public object U_SYP_MDDT { get; set; }
        public object U_SYP_MDFN { get; set; }
        public object U_SYP_MDFC { get; set; }
        public object U_SYP_MDVN { get; set; }
        public object U_SYP_MDVC { get; set; }
        public object U_SYP_MDVT { get; set; }
        public object U_SYP_MDCI { get; set; }
        public string U_SYP_MDTS { get; set; }
        public string U_SYP_TPOENTME { get; set; }
        public object U_SYP_ALMACENERO { get; set; }
        public object U_SYP_SOLICITANTE { get; set; }
        public string U_SYP_TPOSALME { get; set; }
        public string U_SYP_RQORIGEN { get; set; }
        public object U_SYP_NROREQINT { get; set; }
        public object U_SYP_NROSUNAT { get; set; }
        public object U_SYP_VALFOBEXP { get; set; }
        public object U_SYP_MDCF { get; set; }
        public object U_SYP_PROVJRNL { get; set; }
        public string U_SYP_CONSIGNADOR { get; set; }
        public string U_SYP_GRFT { get; set; }
        public string U_SYP_TIPO_TRANSF { get; set; }
        public object U_SYP_TRANS_ENV { get; set; }
        public object U_SYP_SERRET { get; set; }
        public object U_SYP_CODSNERCC { get; set; }
        public object U_SYP_DOCDT { get; set; }
        public object U_SYP_DOCDTT { get; set; }
        public object U_SYP_DLOTE { get; set; }
        public string U_SYP_TPO_OP { get; set; }
        public string U_SYP_FEESTADO { get; set; }
        public object U_SYP_FERPTA { get; set; }
        public object U_SYP_FEMOT { get; set; }
        public string U_SYP_FECAT07 { get; set; }
        public string U_SYP_FECAT09 { get; set; }
        public string U_SYP_FECAT10 { get; set; }
        public string U_SYP_FECAT17 { get; set; }
        public string U_SYP_FECAT12 { get; set; }
        public string U_SYP_FECAT15 { get; set; }
        public string U_SYP_ESTDOC_LE { get; set; }
        public object U_SYP_FECHA_LE { get; set; }
        public string U_SYP_DOCEXPORT { get; set; }
        public object U_SYP_TIPDOCCF { get; set; }
        public object U_SYP_EXONDOM { get; set; }
        public object U_SYP_TIPRTAND { get; set; }
        public object U_SYP_MODSRVND { get; set; }
        public string U_SYP_PNPART76 { get; set; }
        public string U_SYP_BIESRVADQ { get; set; }
        public object U_SYP_CONTRPRY { get; set; }
        public string U_SYP_NCDSTO { get; set; }
        public object U_SYP_NCPESND { get; set; }
        public object U_SYP_NUMFORMIMP { get; set; }
        public string U_SYP_TPODISG { get; set; }
        public string U_SYP_FECAT51 { get; set; }
        public string U_SYP_APLIFACT { get; set; }
        public string U_SYP_APLIFACTN { get; set; }
        public string U_SYP_CDRECCLA { get; set; }
        public object U_SYP_CDTDOCORI { get; set; }
        public object U_SYP_CDDOCORI { get; set; }
        public object U_SYP_CDDOCPR { get; set; }
        public object U_SYP_CDJRNLEST { get; set; }
        public string U_SYP_INDRET { get; set; }
        public object U_SYP_CARDCODE { get; set; }
        public string U_SYP_CONSIGNATARIO { get; set; }
        public string U_SYP_MOTTRA { get; set; }
        public object U_SYP_CGT_GRPVENT { get; set; }
        public float U_SYP_LTTOTCJXAC { get; set; }
        public float U_SYP_LTTOTCJACE { get; set; }
        public float U_SYP_LTAUXPER { get; set; }
        public float U_SYP_LTTCCNJ { get; set; }
        public object U_SYP_LTDOCPROLET { get; set; }
        public string U_SYP_DOCSERVPUB { get; set; }
        public object U_SYP_MESFACT { get; set; }
        public object U_SYP_FECINIFACT { get; set; }
        public object U_SYP_FECFINFACT { get; set; }
        public object U_SYP_IDENTENVIOSEE { get; set; }
        public object U_SYP_MOTBAJA { get; set; }
        public object U_SYP_CTIPOSERVPUB { get; set; }
        public object U_SYP_NTIPOSERVPUB { get; set; }
        public object U_SYP_NROSUMIN { get; set; }
        public object U_SYP_LECTANT { get; set; }
        public object U_SYP_LECTACT { get; set; }
        public object U_SYP_EXTERNO { get; set; }
        public string U_VIS_TypePur { get; set; }
        public object U_VIS_FileImport { get; set; }
        public object U_VIS_TradeImport { get; set; }
        public object U_SYP_FECAPR { get; set; }
        public string U_SYP_CONMON { get; set; }
        public string U_SYP_ANTPEN { get; set; }
        public string U_SYP_DOCAPR { get; set; }
        public string U_SYP_OCTRA { get; set; }
        public string U_SYP_TIPEXP { get; set; }
        public object U_SYP_DBRQ { get; set; }
        public object U_SYP_DBRQ2 { get; set; }
        public string U_SYP_PNACT { get; set; }
        public string U_PZCreated { get; set; }
        public object U_PZSourceType { get; set; }
        public object U_PZSourceID { get; set; }
        public object U_PZidUsuario { get; set; }
        public object U_PZFolio { get; set; }
        public object U_PZExParameter { get; set; }
        public object U_PZExID { get; set; }
        public object U_PZExID2 { get; set; }
        public object U_PZDelivered { get; set; }
        public object U_PZEditToken { get; set; }
        public object U_PZSAPObjType { get; set; }
        public object U_PZExID3 { get; set; }
        public string U_SYP_INC { get; set; }
        public object U_SYP_NUNFR { get; set; }
        public string U_SYP_UNINEG { get; set; }
        public string U_SYP_CON_STOK { get; set; }
        public string U_SYP_PDTREV { get; set; }
        public string U_SYP_PDTCRE { get; set; }
        public string U_VIT_VENMOS { get; set; }
        public string U_VIST_PROMADIC { get; set; }
        public string U_VIST_SUCUSU { get; set; }
        public string U_VIST_APSOLV { get; set; }
        public string U_VIST_DIS { get; set; }
        public string U_SYP_TVENTA { get; set; }
        public object U_VIS_SalesOrderID { get; set; }
        public object U_VIS_CommentApproval { get; set; }
        public object U_VIS_OVCommentary { get; set; }
        public object U_VIS_EVCommentary { get; set; }
        public object U_VIS_INCommentary { get; set; }
        public string U_VIS_CompleteOV { get; set; }
        public object U_VIST_LEAS { get; set; }
        public string U_VIS_OVRejected { get; set; }
        public object U_VIS_ApprovedBy { get; set; }
        public object U_SYP_DT_CONSOL { get; set; }
        public object U_SYP_DT_FCONSOL { get; set; }
        public object U_SYP_DT_HCONSOL { get; set; }
        public object U_SYP_DT_CORRDES { get; set; }
        public object U_SYP_DT_FCDES { get; set; }
        public object U_SYP_DT_OCUR { get; set; }
        public object U_SYP_DT_AYUDANTE { get; set; }
        public string U_SYP_DT_ESTDES { get; set; }
        public object U_SYP_COMDOCD { get; set; }
        public string U_VIS_AgencyCode { get; set; }
        public string U_VIS_AgencyRUC { get; set; }
        public string U_VIS_AgencyName { get; set; }
        public string U_VIS_AgencyDir { get; set; }
        public string U_VIST_REVASIDSCTO { get; set; }
        public object U_VIS_AgencyUbigeo { get; set; }
        public string U_SYP_VIST_TG { get; set; }
        public object U_SYP_FEHASH { get; set; }
        public object U_SYP_FERESP { get; set; }
        public string U_SYP_FEEST { get; set; }
        public object U_SYP_FEESUNAT { get; set; }
        public object U_SYP_FECDR { get; set; }
        public object U_SYP_FEXML { get; set; }
        public object U_SYP_FEDA { get; set; }
        public string U_SYP_FETO { get; set; }
        public int U_SYP_FEEE { get; set; }
        public float U_SYP_FEMEX { get; set; }
        public string U_SYP_FEMB { get; set; }
        public object U_SYP_TPONC { get; set; }
        public object U_SYP_MOTNC { get; set; }
        public object U_SYP_TPOND { get; set; }
        public object U_SYP_MOTND { get; set; }
        public int U_SYP_FEANT { get; set; }
        public string U_SYP_FEGDRT { get; set; }
        public object U_SYP_FEGDRN { get; set; }
        public int U_SYP_FEGIT { get; set; }
        public float U_SYP_FEGPB { get; set; }
        public object U_SYP_FEGNB { get; set; }
        public string U_SYP_FEGMT { get; set; }
        public object U_SYP_FEGFI { get; set; }
        public object U_SYP_FEGFE { get; set; }
        public object U_SYP_FEGNC { get; set; }
        public object U_SYP_FEGPC { get; set; }
        public object U_SYP_FEG3C { get; set; }
        public object U_SYP_FEG3R { get; set; }
        public object U_SYP_FEG3N { get; set; }
        public object U_SYP_FEG3DC { get; set; }
        public object U_SYP_FEG3D { get; set; }
        public object U_SYP_FEG3U { get; set; }
        public object U_SYP_DIRCL { get; set; }
        public object U_VIS_SlpCode { get; set; }
        public object U_VIS_ShipToCode { get; set; }
        public string U_VIS_TypeRequest { get; set; }
        public object U_SYP_FEGTC { get; set; }
        public object U_SYP_FEGTR { get; set; }
        public object U_SYP_FEGTN { get; set; }
        public object U_SYP_FEOBS { get; set; }
        public object U_SYP_FEGCC { get; set; }
        public object U_SYP_FEGCD { get; set; }
        public object U_LB_NROTRANSIT { get; set; }
        public object U_LB_CONTROLADD { get; set; }
        public string U_VIS_TransferType { get; set; }
        public object U_VIS_TransferComment { get; set; }
        public string U_VIS_MTDev { get; set; }
        public string U_VIS_MTReq { get; set; }
        public object U_CODCTRL { get; set; }
        public object U_SERIECOD { get; set; }
        public object U_NROAUTOR { get; set; }
        public object U_NIT { get; set; }
        public object U_FECHALIM { get; set; }
        public string U_LB_WITHCC { get; set; }
        public string U_VIS_Corp_Linea { get; set; }
        public object U_VIS_AppVersion { get; set; }
        public float U_VIS_Intent { get; set; }
        public object U_VIS_Brand { get; set; }
        public object U_VIS_Model { get; set; }
        public object U_VIS_Version { get; set; }
        public string U_SYP_GUIARESU { get; set; }
        public object U_SYP_GRSERIE { get; set; }
        public object U_SYP_GRCORREL { get; set; }
        public object U_SYP_FEPDF { get; set; }
        public string U_CancelReason { get; set; }
        public object[] Document_ApprovalRequests { get; set; }
        public Documentline[] DocumentLines { get; set; }
        public object[] ElectronicProtocols { get; set; }
        public object[] DocumentAdditionalExpenses { get; set; }
        public object[] DocumentSpecialLines { get; set; }
        public Taxextension TaxExtension { get; set; }
        public Addressextension AddressExtension { get; set; }
        public object[] DocumentReferences { get; set; }
    }

    public class Taxextension
    {
        public object TaxId0 { get; set; }
        public object TaxId1 { get; set; }
        public object TaxId2 { get; set; }
        public object TaxId3 { get; set; }
        public object TaxId4 { get; set; }
        public object TaxId5 { get; set; }
        public object TaxId6 { get; set; }
        public object TaxId7 { get; set; }
        public object TaxId8 { get; set; }
        public object TaxId9 { get; set; }
        public object State { get; set; }
        public object County { get; set; }
        public object Incoterms { get; set; }
        public object Vehicle { get; set; }
        public object VehicleState { get; set; }
        public object NFRef { get; set; }
        public object Carrier { get; set; }
        public object PackQuantity { get; set; }
        public object PackDescription { get; set; }
        public object Brand { get; set; }
        public object ShipUnitNo { get; set; }
        public float NetWeight { get; set; }
        public float GrossWeight { get; set; }
        public string StreetS { get; set; }
        public string BlockS { get; set; }
        public string BuildingS { get; set; }
        public string CityS { get; set; }
        public string ZipCodeS { get; set; }
        public string CountyS { get; set; }
        public object StateS { get; set; }
        public string CountryS { get; set; }
        public string StreetB { get; set; }
        public string BlockB { get; set; }
        public string BuildingB { get; set; }
        public string CityB { get; set; }
        public string ZipCodeB { get; set; }
        public string CountyB { get; set; }
        public object StateB { get; set; }
        public string CountryB { get; set; }
        public object ImportOrExport { get; set; }
        public object MainUsage { get; set; }
        public object GlobalLocationNumberS { get; set; }
        public object GlobalLocationNumberB { get; set; }
        public object TaxId12 { get; set; }
        public object TaxId13 { get; set; }
        public object BillOfEntryNo { get; set; }
        public object BillOfEntryDate { get; set; }
        public object OriginalBillOfEntryNo { get; set; }
        public object OriginalBillOfEntryDate { get; set; }
        public string ImportOrExportType { get; set; }
        public object PortCode { get; set; }
        public int DocEntry { get; set; }
        public float BoEValue { get; set; }
        public object ClaimRefund { get; set; }
        public object DifferentialOfTaxRate { get; set; }
        public string IsIGSTAccount { get; set; }
    }

    public class Addressextension
    {
        public string ShipToStreet { get; set; }
        public object ShipToStreetNo { get; set; }
        public string ShipToBlock { get; set; }
        public string ShipToBuilding { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToZipCode { get; set; }
        public string ShipToCounty { get; set; }
        public object ShipToState { get; set; }
        public string ShipToCountry { get; set; }
        public object ShipToAddressType { get; set; }
        public string BillToStreet { get; set; }
        public object BillToStreetNo { get; set; }
        public string BillToBlock { get; set; }
        public string BillToBuilding { get; set; }
        public string BillToCity { get; set; }
        public string BillToZipCode { get; set; }
        public string BillToCounty { get; set; }
        public object BillToState { get; set; }
        public string BillToCountry { get; set; }
        public object BillToAddressType { get; set; }
        public object ShipToGlobalLocationNumber { get; set; }
        public object BillToGlobalLocationNumber { get; set; }
        public object ShipToAddress2 { get; set; }
        public object ShipToAddress3 { get; set; }
        public object BillToAddress2 { get; set; }
        public object BillToAddress3 { get; set; }
        public object PlaceOfSupply { get; set; }
        public object PurchasePlaceOfSupply { get; set; }
        public int DocEntry { get; set; }
        public object GoodsIssuePlaceBP { get; set; }
        public object GoodsIssuePlaceCNPJ { get; set; }
        public object GoodsIssuePlaceCPF { get; set; }
        public object GoodsIssuePlaceStreet { get; set; }
        public object GoodsIssuePlaceStreetNo { get; set; }
        public object GoodsIssuePlaceBuilding { get; set; }
        public object GoodsIssuePlaceZip { get; set; }
        public object GoodsIssuePlaceBlock { get; set; }
        public object GoodsIssuePlaceCity { get; set; }
        public object GoodsIssuePlaceCounty { get; set; }
        public object GoodsIssuePlaceState { get; set; }
        public object GoodsIssuePlaceCountry { get; set; }
        public object GoodsIssuePlacePhone { get; set; }
        public object GoodsIssuePlaceEMail { get; set; }
        public object GoodsIssuePlaceDepartureDate { get; set; }
        public object DeliveryPlaceBP { get; set; }
        public object DeliveryPlaceCNPJ { get; set; }
        public object DeliveryPlaceCPF { get; set; }
        public object DeliveryPlaceStreet { get; set; }
        public object DeliveryPlaceStreetNo { get; set; }
        public object DeliveryPlaceBuilding { get; set; }
        public object DeliveryPlaceZip { get; set; }
        public object DeliveryPlaceBlock { get; set; }
        public object DeliveryPlaceCity { get; set; }
        public object DeliveryPlaceCounty { get; set; }
        public object DeliveryPlaceState { get; set; }
        public object DeliveryPlaceCountry { get; set; }
        public object DeliveryPlacePhone { get; set; }
        public object DeliveryPlaceEMail { get; set; }
        public object DeliveryPlaceDepartureDate { get; set; }
        public string U_VIS_TerritoryIDS { get; set; }
        public string U_VIS_TerritoryIDB { get; set; }
        public string U_VIS_VisitOrderS { get; set; }
        public string U_VIS_VisitOrderB { get; set; }
        public string U_VIS_SlpCodeS { get; set; }
        public string U_VIS_SlpCodeB { get; set; }
        public string U_VIS_ActiveAddressS { get; set; }
        public string U_VIS_ActiveAddressB { get; set; }
        public object U_VIS_SlpNameS { get; set; }
        public object U_VIS_SlpNameB { get; set; }
        public object U_VIS_RefAddressS { get; set; }
        public object U_VIS_RefAddressB { get; set; }
        public string U_VIS_AddressOldS { get; set; }
        public object U_VIS_AddressOldB { get; set; }
        public object U_VIS_LatitudeS { get; set; }
        public object U_VIS_LatitudeB { get; set; }
        public object U_VIS_LongitudeS { get; set; }
        public object U_VIS_LongitudeB { get; set; }
    }

    public class Documentline
    {
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public float Quantity { get; set; }
        public object ShipDate { get; set; }
        public float Price { get; set; }
        public float PriceAfterVAT { get; set; }
        public string Currency { get; set; }
        public float Rate { get; set; }
        public float DiscountPercent { get; set; }
        public string VendorNum { get; set; }
        public object SerialNum { get; set; }
        public string WarehouseCode { get; set; }
        public int SalesPersonCode { get; set; }
        public float CommisionPercent { get; set; }
        public string TreeType { get; set; }
        public string AccountCode { get; set; }
        public string UseBaseUnits { get; set; }
        public string SupplierCatNum { get; set; }
        public string CostingCode { get; set; }
        public string ProjectCode { get; set; }
        public string BarCode { get; set; }
        public string VatGroup { get; set; }
        public float Height1 { get; set; }
        public object Hight1Unit { get; set; }
        public float Height2 { get; set; }
        public object Height2Unit { get; set; }
        public float Lengh1 { get; set; }
        public object Lengh1Unit { get; set; }
        public float Lengh2 { get; set; }
        public object Lengh2Unit { get; set; }
        public float Weight1 { get; set; }
        public object Weight1Unit { get; set; }
        public float Weight2 { get; set; }
        public object Weight2Unit { get; set; }
        public float Factor1 { get; set; }
        public float Factor2 { get; set; }
        public float Factor3 { get; set; }
        public float Factor4 { get; set; }
        public int BaseType { get; set; }
        public object BaseEntry { get; set; }
        public object BaseLine { get; set; }
        public float Volume { get; set; }
        public int VolumeUnit { get; set; }
        public float Width1 { get; set; }
        public object Width1Unit { get; set; }
        public float Width2 { get; set; }
        public object Width2Unit { get; set; }
        public string Address { get; set; }
        public string TaxCode { get; set; }
        public string TaxType { get; set; }
        public string TaxLiable { get; set; }
        public string PickStatus { get; set; }
        public float PickQuantity { get; set; }
        public object PickListIdNumber { get; set; }
        public object OriginalItem { get; set; }
        public object BackOrder { get; set; }
        public string FreeText { get; set; }
        public int ShippingMethod { get; set; }
        public object POTargetNum { get; set; }
        public string POTargetEntry { get; set; }
        public object POTargetRowNum { get; set; }
        public string CorrectionInvoiceItem { get; set; }
        public float CorrInvAmountToStock { get; set; }
        public float CorrInvAmountToDiffAcct { get; set; }
        public float AppliedTax { get; set; }
        public float AppliedTaxFC { get; set; }
        public float AppliedTaxSC { get; set; }
        public string WTLiable { get; set; }
        public string DeferredTax { get; set; }
        public float EqualizationTaxPercent { get; set; }
        public float TotalEqualizationTax { get; set; }
        public float TotalEqualizationTaxFC { get; set; }
        public float TotalEqualizationTaxSC { get; set; }
        public float NetTaxAmount { get; set; }
        public float NetTaxAmountFC { get; set; }
        public float NetTaxAmountSC { get; set; }
        public string MeasureUnit { get; set; }
        public float UnitsOfMeasurment { get; set; }
        public float LineTotal { get; set; }
        public float TaxPercentagePerRow { get; set; }
        public float TaxTotal { get; set; }
        public string ConsumerSalesForecast { get; set; }
        public float ExciseAmount { get; set; }
        public float TaxPerUnit { get; set; }
        public float TotalInclTax { get; set; }
        public object CountryOrg { get; set; }
        public string SWW { get; set; }
        public object TransactionType { get; set; }
        public string DistributeExpense { get; set; }
        public float RowTotalFC { get; set; }
        public float RowTotalSC { get; set; }
        public float LastBuyInmPrice { get; set; }
        public float LastBuyDistributeSumFc { get; set; }
        public float LastBuyDistributeSumSc { get; set; }
        public float LastBuyDistributeSum { get; set; }
        public float StockDistributesumForeign { get; set; }
        public float StockDistributesumSystem { get; set; }
        public float StockDistributesum { get; set; }
        public float StockInmPrice { get; set; }
        public string PickStatusEx { get; set; }
        public float TaxBeforeDPM { get; set; }
        public float TaxBeforeDPMFC { get; set; }
        public float TaxBeforeDPMSC { get; set; }
        public object CFOPCode { get; set; }
        public object CSTCode { get; set; }
        public object Usage { get; set; }
        public string TaxOnly { get; set; }
        public int VisualOrder { get; set; }
        public float BaseOpenQuantity { get; set; }
        public float UnitPrice { get; set; }
        public string LineStatus { get; set; }
        public float PackageQuantity { get; set; }
        public string Text { get; set; }
        public string LineType { get; set; }
        public string COGSCostingCode { get; set; }
        public string COGSAccountCode { get; set; }
        public string ChangeAssemlyBoMWarehouse { get; set; }
        public float GrossBuyPrice { get; set; }
        public int GrossBase { get; set; }
        public float GrossProfitTotalBasePrice { get; set; }
        public string CostingCode2 { get; set; }
        public string CostingCode3 { get; set; }
        public object CostingCode4 { get; set; }
        public object CostingCode5 { get; set; }
        public object ItemDetails { get; set; }
        public object LocationCode { get; set; }
        public object ActualDeliveryDate { get; set; }
        public float RemainingOpenQuantity { get; set; }
        public float OpenAmount { get; set; }
        public float OpenAmountFC { get; set; }
        public float OpenAmountSC { get; set; }
        public object ExLineNo { get; set; }
        public object RequiredDate { get; set; }
        public float RequiredQuantity { get; set; }
        public string COGSCostingCode2 { get; set; }
        public string COGSCostingCode3 { get; set; }
        public object COGSCostingCode4 { get; set; }
        public object COGSCostingCode5 { get; set; }
        public object CSTforIPI { get; set; }
        public object CSTforPIS { get; set; }
        public object CSTforCOFINS { get; set; }
        public object CreditOriginCode { get; set; }
        public string WithoutInventoryMovement { get; set; }
        public object AgreementNo { get; set; }
        public object AgreementRowNumber { get; set; }
        public object ActualBaseEntry { get; set; }
        public object ActualBaseLine { get; set; }
        public int DocEntry { get; set; }
        public float Surpluses { get; set; }
        public float DefectAndBreakup { get; set; }
        public float Shortages { get; set; }
        public string ConsiderQuantity { get; set; }
        public string PartialRetirement { get; set; }
        public float RetirementQuantity { get; set; }
        public float RetirementAPC { get; set; }
        public string ThirdParty { get; set; }
        public object PoNum { get; set; }
        public object PoItmNum { get; set; }
        public object ExpenseType { get; set; }
        public object ReceiptNumber { get; set; }
        public object ExpenseOperationType { get; set; }
        public object FederalTaxID { get; set; }
        public float GrossProfit { get; set; }
        public float GrossProfitFC { get; set; }
        public float GrossProfitSC { get; set; }
        public string PriceSource { get; set; }
        public object StgSeqNum { get; set; }
        public object StgEntry { get; set; }
        public object StgDesc { get; set; }
        public int UoMEntry { get; set; }
        public string UoMCode { get; set; }
        public float InventoryQuantity { get; set; }
        public float RemainingOpenInventoryQuantity { get; set; }
        public object ParentLineNum { get; set; }
        public int Incoterms { get; set; }
        public int TransportMode { get; set; }
        public object NatureOfTransaction { get; set; }
        public object DestinationCountryForImport { get; set; }
        public object DestinationRegionForImport { get; set; }
        public object OriginCountryForExport { get; set; }
        public object OriginRegionForExport { get; set; }
        public string ItemType { get; set; }
        public string ChangeInventoryQuantityIndependently { get; set; }
        public string FreeOfChargeBP { get; set; }
        public object SACEntry { get; set; }
        public object HSNEntry { get; set; }
        public float GrossPrice { get; set; }
        public float GrossTotal { get; set; }
        public float GrossTotalFC { get; set; }
        public float GrossTotalSC { get; set; }
        public int NCMCode { get; set; }
        public object NVECode { get; set; }
        public string IndEscala { get; set; }
        public float CtrSealQty { get; set; }
        public object CNJPMan { get; set; }
        public object UFFiscalBenefitCode { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToDescription { get; set; }
        public object U_SYP_TIPOSERV { get; set; }
        public string U_SYP_ARTINV { get; set; }
        public string U_SYP_HASPROV { get; set; }
        public object U_SYP_CDRDOCEN { get; set; }
        public object U_SYP_CDRLINUM { get; set; }
        public object U_SYP_CLAVEBASE { get; set; }
        public object U_SYP_FECAT07 { get; set; }
        public object U_SYP_FECAT08 { get; set; }
        public object U_SYP_FECAT11 { get; set; }
        public object U_SYP_FECAT14 { get; set; }
        public object U_SYP_FECAT16 { get; set; }
        public object U_SYP_FECAT17 { get; set; }
        public object U_SYP_TPODISC { get; set; }
        public object U_SYP_CGT_PROV { get; set; }
        public object U_SYP_CTIPOSERVPUB { get; set; }
        public object U_SYP_NTIPOSERVPUB { get; set; }
        public object U_SYP_NROSUMIN { get; set; }
        public object U_SYP_LECTANT { get; set; }
        public object U_SYP_LECTACT { get; set; }
        public object U_SYP_EXTERNO { get; set; }
        public object U_SYP_EXT_LINEA { get; set; }
        public object U_VIS_StockReq { get; set; }
        public object U_VIS_UseAvg { get; set; }
        public object U_VIS_StockRefAGV { get; set; }
        public object U_VIS_CommentText { get; set; }
        public object U_SYP_ARTEST { get; set; }
        public object U_PZDeliveredQty { get; set; }
        public object U_PZReturnedQty { get; set; }
        public object U_VIST_CTAINGDCTO { get; set; }
        public object U_VIS_PromID { get; set; }
        public object U_VIS_PromLineID { get; set; }
        public object U_SYP_NUNFR { get; set; }
        public object U_VIST_TIPO { get; set; }
        public object U_SYP_FEDA { get; set; }
        public int U_SYP_FEUICS { get; set; }
        public int U_SYP_LINEAPDF { get; set; }
        public float U_SYP_FETVI { get; set; }
        public float U_SYP_FETVU { get; set; }
        public float U_SYP_FETPU { get; set; }
        public float U_SYP_FETIM { get; set; }
        public object U_VIS_QtySRV { get; set; }
        public object U_VIS_DiscountSRV { get; set; }
        public object U_VIS_ItemCodeSRV { get; set; }
        public object U_VIS_PriceSRV { get; set; }
        public object U_SYP_FEDA2 { get; set; }
        public object U_VIS_MOTDESCOST { get; set; }
        public object U_VIS_MOTDESNEGO { get; set; }
        public object U_VIS_PrcntMarginGain { get; set; }
        public object U_QtySugerida { get; set; }
        
        public Linetaxjurisdiction[] LineTaxJurisdictions { get; set; }
        public object[] DocumentLineAdditionalExpenses { get; set; }
    }

    public class Linetaxjurisdiction
    {
        public string JurisdictionCode { get; set; }
        public int JurisdictionType { get; set; }
        public float TaxAmount { get; set; }
        public float TaxAmountSC { get; set; }
        public float TaxAmountFC { get; set; }
        public float TaxRate { get; set; }
        public int DocEntry { get; set; }
        public int LineNumber { get; set; }
        public int RowSequence { get; set; }
        public float ExternalCalcTaxRate { get; set; }
        public float ExternalCalcTaxAmount { get; set; }
        public float ExternalCalcTaxAmountFC { get; set; }
        public float ExternalCalcTaxAmountSC { get; set; }
    }


}
