using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApiNetCore.BO
{
     public class DocumentLineSD
     {
        public int BaseType { get; set; }
        public int BaseEntry { get; set; }
        public int BaseLine { get; set; }
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public double Quantity { get; set; }
        public double Price { get; set; }
        public double DiscountPercent { get; set; }
        public string WarehouseCode { get; set; }
        public string AccountCode { get; set; }
        public string CostingCode { get; set; }
        public string TaxCode { get; set; }
        public string COGSCostingCode { get; set; }
        public string CostingCode2 { get; set; }
        public string CostingCode3 { get; set; }
        public string COGSCostingCode2 { get; set; }
        public string COGSCostingCode3 { get; set; }
        public string U_SYP_HASPROV { get; set; }
        public string U_SYP_FECAT07 { get; set; }
        public string U_VIST_CTAINGDCTO { get; set; }
        public string U_VIS_PromID { get; set; }
        public string U_VIS_PromLineID { get; set; }
        public string TaxOnly { get; set; }
        
    }
     public class SolicitudDevolucion
    {
        public string DocType { get; set; }
        public string DocDate { get; set; }
        public string DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string NumAtCard { get; set; }
        public string DocCurrency { get; set; }
        public string Comments { get; set; }
        public string DocObjectCode { get; set; }
        public int PaymentGroupCode { get; set; }
        public int SalesPersonCode { get; set; }
        public int DocumentsOwner { get; set; }
        public int Series { get; set; }
        public string TaxDate { get; set; }
        public string DocstringCode { get; set; }
        public string ShipToCode { get; set; }
        public string PayToCode { get; set; }
        public string U_SYP_MDMT { get; set; }
        public string U_SYP_MDTD { get; set; }
        public string U_SYP_MDSD { get; set; }
        public string U_SYP_MDCD { get; set; }
        public string U_SYP_STATUS { get; set; }
        public string U_SYP_MDTO { get; set; }
        public string U_SYP_MDSO { get; set; }
        public string U_SYP_MDCO { get; set; }
        public string U_SYP_FECHAREF { get; set; }
        public string U_SYP_MOTNCND { get; set; }
        public string U_SYP_DETPAGADO { get; set; }
        public string U_SYP_AUTODET { get; set; }
        public string U_SYP_DETPAY { get; set; }
        public string U_SYP_NGUIA { get; set; }
        public string U_SYP_NOCCLIENTE { get; set; }
        public string U_SYP_NANTICIPO { get; set; }
        public string U_SYP_TCOMPRA { get; set; }
        public string U_SYP_ANTICIPO { get; set; }
        public double U_SYP_PANTICIPO { get; set; }
        public string U_SYP_COTPROV { get; set; }
        public string U_SYP_CARPIMP { get; set; }
        public string U_SYP_DPFC { get; set; }
        public string U_SYP_DPNM { get; set; }
        public string U_SYP_MDFE { get; set; }
        public string U_SYP_MDND { get; set; }
        public string U_SYP_CDAD { get; set; }
        public string U_SYP_MDFD { get; set; }
        public string U_SYP_CODERCC { get; set; }
        public string U_SYP_TREQUE { get; set; }
        public string U_SYP_TIPOBOLETO { get; set; }
        public string U_SYP_TEMBAR { get; set; }
        public string U_SYP_NUMCRET { get; set; }
        public string U_SYP_MDCT { get; set; }
        public string U_SYP_MDRT { get; set; }
        public string U_SYP_MDNT { get; set; }
        public string U_SYP_MDDT { get; set; }
        public string U_SYP_MDFN { get; set; }
        public string U_SYP_MDFC { get; set; }
        public string U_SYP_MDVN { get; set; }
        public string U_SYP_MDVC { get; set; }
        public string U_SYP_MDVT { get; set; }
        public string U_SYP_MDCI { get; set; }
        public string U_SYP_MDTS { get; set; }
        public string U_SYP_TPOENTME { get; set; }
        public string U_SYP_ALMACENERO { get; set; }
        public string U_SYP_SOLICITANTE { get; set; }
        public string U_SYP_TPOSALME { get; set; }
        public string U_SYP_RQORIGEN { get; set; }
        public string U_SYP_NROREQINT { get; set; }
        public string U_SYP_NROSUNAT { get; set; }
        public string U_SYP_VALFOBEXP { get; set; }
        public string U_SYP_MDCF { get; set; }
        public string U_SYP_PROVJRNL { get; set; }
        public string U_SYP_CONSIGNADOR { get; set; }
        public string U_SYP_GRFT { get; set; }
        public string U_SYP_TIPO_TRANSF { get; set; }
        public string U_SYP_TRANS_ENV { get; set; }
        public string U_SYP_SERRET { get; set; }
        public string U_SYP_CODSNERCC { get; set; }
        public string U_SYP_DOCDT { get; set; }
        public string U_SYP_DOCDTT { get; set; }
        public string U_SYP_DLOTE { get; set; }
        public string U_SYP_TPO_OP { get; set; }
        public string U_SYP_FEESTADO { get; set; }
        public string U_SYP_FERPTA { get; set; }
        public string U_SYP_FEMOT { get; set; }
        public string U_SYP_FECAT07 { get; set; }
        public string U_SYP_FECAT09 { get; set; }
        public string U_SYP_FECAT10 { get; set; }
        public string U_SYP_FECAT17 { get; set; }
        public string U_SYP_FECAT12 { get; set; }
        public string U_SYP_FECAT15 { get; set; }
        public string U_SYP_ESTDOC_LE { get; set; }
        public string U_SYP_FECHA_LE { get; set; }
        public string U_SYP_DOCEXPORT { get; set; }
        public string U_SYP_TIPDOCCF { get; set; }
        public string U_SYP_EXONDOM { get; set; }
        public string U_SYP_TIPRTAND { get; set; }
        public string U_SYP_MODSRVND { get; set; }
        public string U_SYP_PNPART76 { get; set; }
        public string U_SYP_BIESRVADQ { get; set; }
        public string U_SYP_CONTRPRY { get; set; }
        public string U_SYP_NCDSTO { get; set; }
        public string U_SYP_NCPESND { get; set; }
        public string U_SYP_NUMFORMIMP { get; set; }
        public string U_SYP_TPODISG { get; set; }
        public string U_SYP_FECAT51 { get; set; }
        public string U_SYP_APLIFACT { get; set; }
        public string U_SYP_APLIFACTN { get; set; }
        public string U_SYP_CDRECCLA { get; set; }
        public string U_SYP_CDTDOCORI { get; set; }
        public string U_SYP_CDDOCORI { get; set; }
        public string U_SYP_CDDOCPR { get; set; }
        public string U_SYP_CDJRNLEST { get; set; }
        public string U_SYP_INDRET { get; set; }
        public string U_SYP_CARDCODE { get; set; }
        public string U_SYP_CONSIGNATARIO { get; set; }
        public string U_SYP_MOTTRA { get; set; }
        public string U_SYP_CGT_GRPVENT { get; set; }
        public double U_SYP_LTTOTCJXAC { get; set; }
        public double U_SYP_LTTOTCJACE { get; set; }
        public double U_SYP_LTAUXPER { get; set; }
        public double U_SYP_LTTCCNJ { get; set; }
        public string U_SYP_LTDOCPROLET { get; set; }
        public string U_SYP_DOCSERVPUB { get; set; }
        public string U_SYP_MESFACT { get; set; }
        public string U_SYP_FECINIFACT { get; set; }
        public string U_SYP_FECFINFACT { get; set; }
        public string U_SYP_IDENTENVIOSEE { get; set; }
        public string U_SYP_MOTBAJA { get; set; }
        public string U_SYP_CTIPOSERVPUB { get; set; }
        public string U_SYP_NTIPOSERVPUB { get; set; }
        public string U_SYP_NROSUMIN { get; set; }
        public string U_SYP_LECTANT { get; set; }
        public string U_SYP_LECTACT { get; set; }
        public string U_SYP_EXTERNO { get; set; }
        public string U_VIS_TypePur { get; set; }
        public string U_VIS_FileImport { get; set; }
        public string U_VIS_TradeImport { get; set; }
        public string U_SYP_FECAPR { get; set; }
        public string U_SYP_CONMON { get; set; }
        public string U_SYP_ANTPEN { get; set; }
        public string U_SYP_DOCAPR { get; set; }
        public string U_SYP_OCTRA { get; set; }
        public string U_SYP_TIPEXP { get; set; }
        public string U_SYP_DBRQ { get; set; }
        public string U_SYP_DBRQ2 { get; set; }
        public string U_SYP_PNACT { get; set; }
        public string U_PZCreated { get; set; }
        public string U_PZSourceType { get; set; }
        public string U_PZSourceID { get; set; }
        public string U_PZidUsuario { get; set; }
        public string U_PZFolio { get; set; }
        public string U_PZExParameter { get; set; }
        public string U_PZExID { get; set; }
        public string U_PZExID2 { get; set; }
        public string U_PZDelivered { get; set; }
        public string U_PZEditToken { get; set; }
        public string U_PZSAPObjType { get; set; }
        public string U_PZExID3 { get; set; }
        public string U_SYP_INC { get; set; }
        public string U_SYP_NUNFR { get; set; }
        public string U_SYP_UNINEG { get; set; }
        public string U_SYP_CON_STOK { get; set; }
        public string U_SYP_PDTREV { get; set; }
        public string U_SYP_PDTCRE { get; set; }
        public string U_VIT_VENMOS { get; set; }
        public string U_VIST_PROMADIC { get; set; }
        public string U_VIST_SUCUSU { get; set; }
        public string U_VIST_APSOLV { get; set; }
        public string U_VIST_DIS { get; set; }
        public string U_SYP_TVENTA { get; set; }
        public string U_VIS_SalesOrderID { get; set; }
        public string U_VIS_CommentApproval { get; set; }
        public string U_VIS_OVCommentary { get; set; }
        public string U_VIS_EVCommentary { get; set; }
        public string U_VIS_INCommentary { get; set; }
        public string U_VIS_CompleteOV { get; set; }
        public string U_VIST_LEAS { get; set; }
        public string U_VIS_OVRejected { get; set; }
        public string U_VIS_ApprovedBy { get; set; }
        public string U_SYP_DT_CONSOL { get; set; }
        public string U_SYP_DT_FCONSOL { get; set; }
        public string U_SYP_DT_HCONSOL { get; set; }
        public string U_SYP_DT_CORRDES { get; set; }
        public string U_SYP_DT_FCDES { get; set; }
        public string U_SYP_DT_OCUR { get; set; }
        public string U_SYP_DT_AYUDANTE { get; set; }
        public string U_SYP_DT_ESTDES { get; set; }
        public string U_SYP_COMDOCD { get; set; }
        public string U_VIS_AgencyCode { get; set; }
        public string U_VIS_AgencyRUC { get; set; }
        public string U_VIS_AgencyName { get; set; }
        public string U_VIS_AgencyDir { get; set; }
        public string U_VIST_REVASIDSCTO { get; set; }
        public string U_VIS_AgencyUbigeo { get; set; }
        public string U_SYP_VIST_TG { get; set; }
        public string U_SYP_FEHASH { get; set; }
        public string U_SYP_FERESP { get; set; }
        public string U_SYP_FEEST { get; set; }
        public int U_SYP_FEESUNAT { get; set; }
        public string U_SYP_FECDR { get; set; }
        public string U_SYP_FEXML { get; set; }
        public string U_SYP_FEDA { get; set; }
        public string U_SYP_FETO { get; set; }
        public int U_SYP_FEEE { get; set; }
        public int U_SYP_FEMEX { get; set; }
        public string U_SYP_FEMB { get; set; }
        public string U_SYP_TPONC { get; set; }
        public string U_SYP_MOTNC { get; set; }
        public string U_SYP_TPOND { get; set; }
        public string U_SYP_MOTND { get; set; }
        public int U_SYP_FEANT { get; set; }
        public string U_SYP_FEGDRN { get; set; }
        public int U_SYP_FEGIT { get; set; }
        public double U_SYP_FEGPB { get; set; }
        public string U_SYP_FEGNB { get; set; }
        public string U_SYP_FEGMT { get; set; }
        public string U_SYP_FEGFI { get; set; }
        public string U_SYP_FEGFE { get; set; }
        public string U_SYP_FEGNC { get; set; }
        public string U_SYP_FEG3C { get; set; }
        public string U_SYP_FEG3R { get; set; }
        public string U_SYP_FEG3N { get; set; }
        public string U_SYP_FEG3DC { get; set; }
        public string U_SYP_FEG3D { get; set; }
        public string U_SYP_FEG3U { get; set; }
        public string U_SYP_DIRCL { get; set; }
        public string U_VIS_SlpCode { get; set; }
        public string U_VIS_ShipToCode { get; set; }
        public string U_VIS_TypeRequest { get; set; }
        public string U_SYP_FEOBS { get; set; }
        public string U_SYP_FEGCC { get; set; }
        public string U_SYP_FEGCD { get; set; }
        public string U_LB_NROTRANSIT { get; set; }
        public string U_LB_CONTROLADD { get; set; }
        public string U_VIS_TransferType { get; set; }
        public string U_VIS_TransferComment { get; set; }
        public string U_VIS_MTDev { get; set; }
        public string U_VIS_MTReq { get; set; }
        public string U_CODCTRL { get; set; }
        public string U_SERIECOD { get; set; }
        public string U_NROAUTOR { get; set; }
        public string U_NIT { get; set; }
        public string U_FECHALIM { get; set; }
        public string U_LB_WITHCC { get; set; }
        public string U_VIS_Corp_Linea { get; set; }
        public string U_VIS_AppVersion { get; set; }
        public double U_VIS_Intent { get; set; }
        public string U_VIS_Brand { get; set; }
        public string U_VIS_Model { get; set; }
        public string U_VIS_Version { get; set; }
        public string U_SYP_GUIARESU { get; set; }
        public string U_SYP_GRSERIE { get; set; }
        public string U_SYP_GRCORREL { get; set; }
        public string U_SYP_FEPDF { get; set; }
        public string U_CancelReason { get; set; }
        public string U_CancelReasonOV { get; set; }
        public string U_SYP_MOTNC_COD { get; set; }
        public string U_GroupNum { get; set; }
        public string U_Transfered { get; set; }
        public string U_TaskMigrate { get; set; }
        public string U_VIS_Alert1 { get; set; }
        public string U_VIS_Alert2 { get; set; }
        public string U_VIS_Alert3 { get; set; }
        public string U_VIS_Mensaje1 { get; set; }
        public string U_VIS_Mensaje2 { get; set; }
        public string U_VIS_Mensaje3 { get; set; }
        public double U_VIS_Densidad { get; set; }
        public double U_SYP_FERMN { get; set; }
        public string U_SYP_FEGDRT { get; set; }
        public double U_SYP_FEGPBC { get; set; }
        public string U_SYP_FEGUC { get; set; }
        public string U_SYP_FEGNP { get; set; }
        public string U_SYP_FEGPC { get; set; }
        public string U_SYP_FEGAC { get; set; }
        public string U_SYP_FEGAO { get; set; }
        public string U_SYP_FEGAD { get; set; }
        public string U_VIS_Route { get; set; }
        public string U_SYP_FEDTC { get; set; }
        public string U_SYP_FEDTP { get; set; }
        public double U_SYP_FEDTM { get; set; }
        public string U_VIS_MOTAPLDESC { get; set; }
        public string U_VIS_TipTransGrat { get; set; }
        public string U_VIS_DT_ESTDES_CONF { get; set; }
        public string U_U_VIS_DT_OCUR_CONF { get; set; }
        public string U_U_VIS_DT_COMENT_CONF { get; set; }
        public int U_VIS_Flete { get; set; }
        public double U_VIS_PrcntMarginGain { get; set; }
        public string U_VIS_StatusComp { get; set; }
        public string U_VIS_Draft1 { get; set; }
        public double U_RateRef { get; set; }
        public string U_SYP_FEEB { get; set; }
        public string U_SYP_FEEA { get; set; }
        public string U_SYP_FEGDRI { get; set; }
        public int U_SYP_FEGTVM { get; set; }
        public int U_SYP_FEGREV { get; set; }
        public int U_SYP_FEGRVV { get; set; }
        public int U_SYP_FEGTDS { get; set; }
        public int U_SYP_FEGVCT { get; set; }
        public string U_SYP_FEATC { get; set; }
        public string U_SYP_FEATR { get; set; }
        public string U_SYP_FEATN { get; set; }
        public string U_SYP_FEATDC { get; set; }
        public string U_SYP_FEATD { get; set; }
        public string U_SYP_FEATU { get; set; }
        public string U_SYP_FEGES { get; set; }
        public string U_SYP_FEGAF { get; set; }
        public string U_SYP_FEGRD { get; set; }
        public string U_Confirma_Pedido_Dup { get; set; }
        public string U_VIS_RESP_SUNAT { get; set; }
        public double U_VIS_DiscountPercent { get; set; }
        public string U_VIS_ReasonDiscountPercent { get; set; }
        public string U_TrasvaseRef { get; set; }
        public string U_VIS_FechaConsolVent { get; set; }
        public string U_VIS_SCM_BaseEntry { get; set; }
        public string U_USERID { get; set; }
        public string U_FechaCompromisoEntrega { get; set; }
        public string U_MotivIncum_OnTime { get; set; }
        public string U_Regularizacion_Contabilidad { get; set; }
        public int U_UpdateUser { get; set; }
        public string U_LogChange { get; set; }
        public string U_VIS_BossValidation { get; set; }
        public string U_Wms_Ticket { get; set; }
        public string U_VIS_DeliveryDateOptional { get; set; }
        public string U_release { get; set; }
        public string U_ReleaseID { get; set; }
        public string U_ReleaseDate { get; set; }
        public string U_ApprovedHour { get; set; }
        public string U_ID_Document { get; set; }
        public string U_CommentsAp1 { get; set; }
        public string U_CommentsAp2 { get; set; }
        public string U_CommentsAp3 { get; set; }
        public List<DocumentLineSD> DocumentLines { get; set; }

    }

}
